// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmvmwnppfgeziqaqsuzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdm13bnBwZmdlemlxYXFzdXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjQ3NTEsImV4cCI6MjA2Mzg0MDc1MX0.L5iLBkK8G_N5AgwOAKDVNXMcOqu5SmgJFb-w4fGU4co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);